//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikeRental.ClientApp.BikeRentalService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BikeRentalService.IBikeRentalService")]
    public interface IBikeRentalService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBikeRentalService/AddUser", ReplyAction="http://tempuri.org/IBikeRentalService/AddUserResponse")]
        string AddUser(string login, string password, string name, string surname, string phone, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBikeRentalService/AddUser", ReplyAction="http://tempuri.org/IBikeRentalService/AddUserResponse")]
        System.Threading.Tasks.Task<string> AddUserAsync(string login, string password, string name, string surname, string phone, string address);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBikeRentalService/Login", ReplyAction="http://tempuri.org/IBikeRentalService/LoginResponse")]
        string Login([System.ServiceModel.MessageParameterAttribute(Name="login")] string login1, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBikeRentalService/Login", ReplyAction="http://tempuri.org/IBikeRentalService/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBikeRentalService/AddBike", ReplyAction="http://tempuri.org/IBikeRentalService/AddBikeResponse")]
        void AddBike(string brand, string model, string type, string color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBikeRentalService/AddBike", ReplyAction="http://tempuri.org/IBikeRentalService/AddBikeResponse")]
        System.Threading.Tasks.Task AddBikeAsync(string brand, string model, string type, string color);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBikeRentalService/AddRent", ReplyAction="http://tempuri.org/IBikeRentalService/AddRentResponse")]
        void AddRent(int userID, int bikeID, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBikeRentalService/AddRent", ReplyAction="http://tempuri.org/IBikeRentalService/AddRentResponse")]
        System.Threading.Tasks.Task AddRentAsync(int userID, int bikeID, int price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBikeRentalService/GetUserID", ReplyAction="http://tempuri.org/IBikeRentalService/GetUserIDResponse")]
        int GetUserID(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBikeRentalService/GetUserID", ReplyAction="http://tempuri.org/IBikeRentalService/GetUserIDResponse")]
        System.Threading.Tasks.Task<int> GetUserIDAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBikeRentalService/ReturnBike", ReplyAction="http://tempuri.org/IBikeRentalService/ReturnBikeResponse")]
        void ReturnBike(int bikeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBikeRentalService/ReturnBike", ReplyAction="http://tempuri.org/IBikeRentalService/ReturnBikeResponse")]
        System.Threading.Tasks.Task ReturnBikeAsync(int bikeID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBikeRentalService/AddRepairOrder", ReplyAction="http://tempuri.org/IBikeRentalService/AddRepairOrderResponse")]
        void AddRepairOrder(int bikeID, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBikeRentalService/AddRepairOrder", ReplyAction="http://tempuri.org/IBikeRentalService/AddRepairOrderResponse")]
        System.Threading.Tasks.Task AddRepairOrderAsync(int bikeID, string description);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBikeRentalServiceChannel : BikeRental.ClientApp.BikeRentalService.IBikeRentalService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BikeRentalServiceClient : System.ServiceModel.ClientBase<BikeRental.ClientApp.BikeRentalService.IBikeRentalService>, BikeRental.ClientApp.BikeRentalService.IBikeRentalService {
        
        public BikeRentalServiceClient() {
        }
        
        public BikeRentalServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BikeRentalServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BikeRentalServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BikeRentalServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddUser(string login, string password, string name, string surname, string phone, string address) {
            return base.Channel.AddUser(login, password, name, surname, phone, address);
        }
        
        public System.Threading.Tasks.Task<string> AddUserAsync(string login, string password, string name, string surname, string phone, string address) {
            return base.Channel.AddUserAsync(login, password, name, surname, phone, address);
        }
        
        public string Login(string login1, string password) {
            return base.Channel.Login(login1, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string login, string password) {
            return base.Channel.LoginAsync(login, password);
        }
        
        public void AddBike(string brand, string model, string type, string color) {
            base.Channel.AddBike(brand, model, type, color);
        }
        
        public System.Threading.Tasks.Task AddBikeAsync(string brand, string model, string type, string color) {
            return base.Channel.AddBikeAsync(brand, model, type, color);
        }
        
        public void AddRent(int userID, int bikeID, int price) {
            base.Channel.AddRent(userID, bikeID, price);
        }
        
        public System.Threading.Tasks.Task AddRentAsync(int userID, int bikeID, int price) {
            return base.Channel.AddRentAsync(userID, bikeID, price);
        }
        
        public int GetUserID(string login) {
            return base.Channel.GetUserID(login);
        }
        
        public System.Threading.Tasks.Task<int> GetUserIDAsync(string login) {
            return base.Channel.GetUserIDAsync(login);
        }
        
        public void ReturnBike(int bikeID) {
            base.Channel.ReturnBike(bikeID);
        }
        
        public System.Threading.Tasks.Task ReturnBikeAsync(int bikeID) {
            return base.Channel.ReturnBikeAsync(bikeID);
        }
        
        public void AddRepairOrder(int bikeID, string description) {
            base.Channel.AddRepairOrder(bikeID, description);
        }
        
        public System.Threading.Tasks.Task AddRepairOrderAsync(int bikeID, string description) {
            return base.Channel.AddRepairOrderAsync(bikeID, description);
        }
    }
}
